// Command gen-tcgid-override turns a tcgid4scryfall report into the generated
// half of the TCGplayer id-override map.
//
// AnonTCG deviation (not upstream). MTGJSON publishes no tcgplayerProductId at
// all for part of the catalog — 3,810 of our 110,299 entities as of
// 2026-09-24 — and both TCGplayer scrapers gate on that field
// (tcgplayer/index.go enqueues nothing without it; tcgplayer/tcgplayer.go
// skips any uuid absent from TcgplayerSkus.json). Those cards therefore carry
// no TCGplayer price and no sku, which surfaces as $0.00 rows in the sealed
// decklist export.
//
// Upstream already finds the right product for them: cmd/tcgid4scryfall walks
// TCGplayer's catalog, resolves each product back through mtgmatcher, and
// reports where the resolved id disagrees with MTGJSON's. It reports and
// stops. This command turns that report into data the loader applies.
//
// The output is written as a SEPARATE file from the hand-curated
// tcgplayer_id_override.json so regeneration can never clobber an entry a
// human reasoned about (the HOB Gleaming Splendor pair needs an alt-foil
// DELETE, which no report can express). The loader merges both and lets the
// manual file win.
//
// Usage:
//
//	gen-tcgid-override -i tcgid4scryfall.csv [-allprintings AllPrintings.json]
//	gen-tcgid-override -i tcgid4scryfall.csv -check
package main

import (
	"encoding/csv"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

const defaultOutput = "mtgmatcher/magic/tcgplayer_id_override_generated.json"

const fileComment = "GENERATED by cmd/gen-tcgid-override from a cmd/tcgid4scryfall report. " +
	"Do not hand-edit: regenerate instead. Hand-curated entries belong in " +
	"tcgplayer_id_override.json, which wins on conflict."

var (
	inputOpt        = flag.String("i", "", "tcgid4scryfall CSV report (required)")
	allPrintingsOpt = flag.String("allprintings", "allprintings5.json", "AllPrintings file path")
	outputOpt       = flag.String("o", defaultOutput, "output path")
	checkOpt        = flag.Bool("check", false, "compare against the existing file(s) and fail on drift instead of writing")

	// The same map has a second consumer in AnonTCG-ETL, which backfills
	// mtg_entities.identifiers so the decklist export's sku lookup (the
	// tcgplayer_catalog join in _tcg_mass_entry_rows) can resolve. That job
	// runs on a runner that never checks this repo out, so it needs its own
	// copy. Both are written by one command so the two cannot drift.
	etlOutputOpt = flag.String("etl-o", "",
		"also write the identical map here (AnonTCG-ETL overlay path)")
)

// entry mirrors magic.tcgIDOverrideEntry. It is duplicated rather than
// imported because the loader's copy is unexported, and an exported
// generator-facing type in that package would widen the deviation surface for
// no gain.
type entry struct {
	Set             string `json:"set"`
	Name            string `json:"name"`
	Number          string `json:"number"`
	Primary         string `json:"primary"`
	AltFoil         string `json:"alt_foil"`
	UpstreamPrimary string `json:"upstream_primary"`
	UpstreamAltFoil string `json:"upstream_alt_foil"`
}

type overrideFile struct {
	Comment string           `json:"_comment"`
	Cards   map[string]entry `json:"cards"`
}

// apCard is the slice of an AllPrintings card this command reads. AllPrintings
// is parsed directly rather than through magic.Load because Load applies the
// override map while building, which would make -check compare our own output
// against itself and report drift-free forever.
type apCard struct {
	UUID        string            `json:"uuid"`
	Name        string            `json:"name"`
	Number      string            `json:"number"`
	SetCode     string            `json:"setCode"`
	Identifiers map[string]string `json:"identifiers"`
}

type apFile struct {
	Data map[string]struct {
		Cards  []apCard `json:"cards"`
		Tokens []apCard `json:"tokens"`
	} `json:"data"`
}

// report is one row of the tcgid4scryfall CSV.
type report struct {
	Name       string
	Set        string
	Number     string
	ScryfallID string
	OldID      string
	NewID      string
	NewEtched  string
}

func readReport(path string) ([]report, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	header, err := r.Read()
	if err != nil {
		return nil, fmt.Errorf("reading header: %w", err)
	}
	want := []string{"name", "set", "cn", "scryfall_id", "old_tcgplayer_id", "new_tcgplayer_id", "new_tcgplayer_etched_id"}
	if strings.Join(header, ",") != strings.Join(want, ",") {
		return nil, fmt.Errorf("unexpected header %q, want %q",
			strings.Join(header, ","), strings.Join(want, ","))
	}

	var out []report
	for {
		rec, err := r.Read()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, err
		}
		out = append(out, report{
			Name: rec[0], Set: rec[1], Number: rec[2], ScryfallID: rec[3],
			OldID: rec[4], NewID: rec[5], NewEtched: rec[6],
		})
	}
	return out, nil
}

func readAllPrintings(path string) (map[string][]apCard, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var ap apFile
	if err := json.NewDecoder(f).Decode(&ap); err != nil {
		return nil, fmt.Errorf("decoding %s: %w", path, err)
	}

	// Keyed by scryfallId. A scryfall id is NOT 1:1 with an mtgjson uuid: a
	// split card emits one object per face sharing the id (PLST DSK-3 is
	// "Dazzling Theater" side a and "Prop Room" side b). Both faces are
	// indexed and both get an entry below, because the report cannot say
	// which face the matcher resolved and a missed face is a $0.00 row.
	bySF := map[string][]apCard{}
	for _, set := range ap.Data {
		for _, group := range [][]apCard{set.Cards, set.Tokens} {
			for _, card := range group {
				sf := card.Identifiers["scryfallId"]
				if sf == "" {
					continue
				}
				bySF[sf] = append(bySF[sf], card)
			}
		}
	}
	return bySF, nil
}

func build(reports []report, bySF map[string][]apCard) (map[string]entry, error) {
	cards := map[string]entry{}
	var unmatched []string

	for _, rep := range reports {
		// The override struct carries primary + alt-foil only. An etched
		// product would need tcgplayerEtchedProductId, which it cannot
		// express — refuse rather than silently drop the row.
		if rep.NewEtched != "" {
			return nil, fmt.Errorf("%s (%s #%s): report carries an etched product id (%s), "+
				"which the override struct cannot express; extend it before regenerating",
				rep.Name, rep.Set, rep.Number, rep.NewEtched)
		}
		if rep.NewID == "" {
			return nil, fmt.Errorf("%s (%s #%s): report row has no new product id",
				rep.Name, rep.Set, rep.Number)
		}

		matches := bySF[rep.ScryfallID]
		if len(matches) == 0 {
			unmatched = append(unmatched, fmt.Sprintf("%s (%s #%s) scryfall=%s",
				rep.Name, rep.Set, rep.Number, rep.ScryfallID))
			continue
		}

		for _, card := range matches {
			cards[card.UUID] = entry{
				Set:     card.SetCode,
				Name:    card.Name,
				Number:  card.Number,
				Primary: rep.NewID,
				// The report never asks for an alt-foil product, and an empty
				// value means "delete the field". For a card MTGJSON never
				// mapped there is no field to delete, so this is a no-op; for
				// the handful whose primary is merely wrong it preserves the
				// existing single-product shape.
				AltFoil: "",
				// What MTGJSON publishes right now. Empty for the missing-id
				// case, which is exactly what classify() needs to report the
				// entry as StillNeeded while upstream stays silent and
				// Redundant once it catches up.
				UpstreamPrimary: card.Identifiers["tcgplayerProductId"],
				UpstreamAltFoil: card.Identifiers["tcgplayerAlternativeFoilProductId"],
			}
		}
	}

	// A report row the datastore cannot place means the two inputs are from
	// different MTGJSON builds. Silently dropping it would quietly shrink the
	// map, so say so.
	if len(unmatched) > 0 {
		return nil, fmt.Errorf("%d report rows matched no card in AllPrintings "+
			"(mismatched MTGJSON builds?): %s", len(unmatched), strings.Join(unmatched, "; "))
	}
	return cards, nil
}

// render serializes deterministically: encoding/json sorts map keys, and the
// trailing newline keeps the file diff-friendly.
func render(cards map[string]entry) ([]byte, error) {
	buf, err := json.MarshalIndent(overrideFile{Comment: fileComment, Cards: cards}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(buf, '\n'), nil
}

func run() error {
	if *inputOpt == "" {
		return errors.New("-i is required")
	}
	allprintings := *allPrintingsOpt
	if env := os.Getenv("ALLPRINTINGS5_PATH"); env != "" {
		allprintings = env
	}

	reports, err := readReport(*inputOpt)
	if err != nil {
		return err
	}
	bySF, err := readAllPrintings(allprintings)
	if err != nil {
		return err
	}
	cards, err := build(reports, bySF)
	if err != nil {
		return err
	}
	out, err := render(cards)
	if err != nil {
		return err
	}

	targets := []string{*outputOpt}
	if *etlOutputOpt != "" {
		targets = append(targets, *etlOutputOpt)
	}

	if *checkOpt {
		for _, target := range targets {
			existing, err := os.ReadFile(target)
			if err != nil {
				return fmt.Errorf("reading %s for -check: %w", target, err)
			}
			if string(existing) != string(out) {
				return fmt.Errorf("%s is out of date (%d entries generated); re-run without -check",
					target, len(cards))
			}
			fmt.Fprintf(os.Stderr, "%s is up to date (%d entries)\n", target, len(cards))
		}
		return nil
	}

	for _, target := range targets {
		if err := os.WriteFile(target, out, 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "wrote %s (%d entries from %d report rows)\n",
			target, len(cards), len(reports))
	}

	// Surface the fan-out so a growing split-card population is visible
	// rather than silently doubling entries.
	if len(cards) != len(reports) {
		fmt.Fprintf(os.Stderr,
			"note: %d entries from %d rows - some scryfall ids cover multiple faces\n",
			len(cards), len(reports))
	}
	return nil
}

func main() {
	flag.Parse()
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-tcgid-override:", err)
		os.Exit(1)
	}
}
